/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2830482421025
 */
public class TelaCalculoAreas extends javax.swing.JFrame {

    private String stringDigitada = "";
    /**
     * Creates new form TelaCalculoAreas
     */
    public TelaCalculoAreas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxTipoFigura = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLargura = new javax.swing.JTextField();
        jTextFieldAltura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCalcularArea = new javax.swing.JButton();
        jButtonCalcularPerimetro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cáculo de Áreas de Figuras Geométricas");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jComboBoxTipoFigura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "quadrado", "retângulo", "círculo", "triângulo" }));

        jLabel1.setText("Tipo de Figura Geométrica");

        jTextFieldLargura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLarguraActionPerformed(evt);
            }
        });
        jTextFieldLargura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLarguraKeyTyped(evt);
            }
        });

        jTextFieldAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAlturaKeyTyped(evt);
            }
        });

        jLabel2.setText("Largura");

        jLabel3.setText("Altura");

        jButtonCalcularArea.setText("Calcular Área");
        jButtonCalcularArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularAreaActionPerformed(evt);
            }
        });

        jButtonCalcularPerimetro.setText("Calcular Perímetro");
        jButtonCalcularPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularPerimetroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxTipoFigura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldLargura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButtonCalcularArea, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(200, 200, 200))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonCalcularPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipoFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcularArea)
                    .addComponent(jButtonCalcularPerimetro))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLarguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLarguraActionPerformed

    private void jButtonCalcularPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularPerimetroActionPerformed
        double largura, altura, perimetro;
        
        largura = Double.parseDouble(jTextFieldLargura.getText());
        altura = Double.parseDouble(jTextFieldAltura.getText());
        
        int indiceEscolhido = jComboBoxTipoFigura.getSelectedIndex();
        
        switch(indiceEscolhido) {
            case 0:
                perimetro = 4 * largura;
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Perímetro do Quadrado: " + String.format("%.2f", perimetro));
                break;
            case 1:
                perimetro = 2 * (largura + altura);
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Perímetro do Retângulo: " + String.format("%.2f", perimetro));
                break;
            case 2:
                perimetro = 2 * Math.PI * largura;
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Perímetro do Círculo: " + String.format("%.2f", perimetro));
                break;
            case 3:
                perimetro = 3 * largura;
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Perímetro do Triângulo: " + String.format("%.2f", perimetro));
                break;
        }
    }//GEN-LAST:event_jButtonCalcularPerimetroActionPerformed

    private void jButtonCalcularAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularAreaActionPerformed
        double largura, altura, area;
        
        largura = Double.parseDouble(jTextFieldLargura.getText());
        altura = Double.parseDouble(jTextFieldAltura.getText());
        
        if(jComboBoxTipoFigura.getSelectedItem().toString() == "quadrado") {
            
            if(largura != altura) {
                javax.swing.JOptionPane.showMessageDialog(this, "Largura e altura de um quadrado devem ser iguais!");
            } else {
                area = largura * altura;
                javax.swing.JOptionPane.showMessageDialog(this, "Área do quadrado calculado é: " + String.format("%.2f", area));            
            }
        }
        else if (jComboBoxTipoFigura.getSelectedItem().toString() == "retângulo") {
            area = largura * altura;
            javax.swing.JOptionPane.showMessageDialog(this, "Área do Retângulo calculado é: " + String.format("%.2f", area));
        }
        else if (jComboBoxTipoFigura.getSelectedItem().toString() == "triângulo") {
            area = (largura * altura) / 2;
            javax.swing.JOptionPane.showMessageDialog(this, "Área do Triângulo calculado é: " + String.format("%.2f", area));
        }
        else {
            if(largura != altura){
                javax.swing.JOptionPane.showMessageDialog(this, "Largura e altura de um círculo devem ser iguais!");
            } else{
                double raio = largura / 2;
            area = Math.PI * raio * raio;
            javax.swing.JOptionPane.showMessageDialog(this, "Área do Círculo calculado é: " + String.format("%.2f", area));
            }
        }
    }//GEN-LAST:event_jButtonCalcularAreaActionPerformed

    private void jTextFieldLarguraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLarguraKeyTyped
        char caractereDigitado = evt.getKeyChar();
        
        if(!Character.isDigit(caractereDigitado) 
                && caractereDigitado != '.') 
        {
            evt.consume(); //impede que o usuário digite letras
        }
    }//GEN-LAST:event_jTextFieldLarguraKeyTyped

    private void jTextFieldAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAlturaKeyTyped
        char caractereDigitado = evt.getKeyChar();
        
        if(!Character.isDigit(caractereDigitado) 
                && caractereDigitado != '.') 
        {
            evt.consume(); //impede que o usuário digite letras
        }
    }//GEN-LAST:event_jTextFieldAlturaKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        /*char caractereDigitado = evt.getKeyChar();
        
        if (caractereDigitado == '@') {
            stringDigitada = "";
        } else {
            stringDigitada = stringDigitada + caractereDigitado;
        }
        
        if (stringDigitada == "senha") {
            javax.swing.JOptionPane.showMessageDialog(this, "Você digitou a senha secreta");
        }*/
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculoAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculoAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculoAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculoAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculoAreas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcularArea;
    private javax.swing.JButton jButtonCalcularPerimetro;
    private javax.swing.JComboBox<String> jComboBoxTipoFigura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldLargura;
    // End of variables declaration//GEN-END:variables
}
