/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2830482421025
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanelFiguraGeometrica = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLadoQuadrado = new javax.swing.JTextField();
        painelDesenhoQuadrado = new PainelDesenho();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldAlturaRetangulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLarguraRetangulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldRaioCircunferencia = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldAlturaTrianguloRetangulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLarguraTrianguloRetangulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldAlturaTrianguloIsoceles = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldLarguraTrianguloIsoceles = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldAX = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldBX = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCX = new javax.swing.JTextField();
        jTextFieldCY = new javax.swing.JTextField();
        jTextFieldBY = new javax.swing.JTextField();
        jTextFieldAY = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jTextFieldBaseParalelogramo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldAlturaParalelogramo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldLadoInclinadoParalelogramo = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lado : ");

        jTextFieldLadoQuadrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLadoQuadradoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout painelDesenhoQuadradoLayout = new javax.swing.GroupLayout(painelDesenhoQuadrado);
        painelDesenhoQuadrado.setLayout(painelDesenhoQuadradoLayout);
        painelDesenhoQuadradoLayout.setHorizontalGroup(
            painelDesenhoQuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        painelDesenhoQuadradoLayout.setVerticalGroup(
            painelDesenhoQuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldLadoQuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(524, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelDesenhoQuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldLadoQuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDesenhoQuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPanelFiguraGeometrica.addTab("Quadrado", jPanel1);

        jTextFieldAlturaRetangulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAlturaRetanguloKeyTyped(evt);
            }
        });

        jLabel2.setText("Altura");

        jTextFieldLarguraRetangulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLarguraRetanguloKeyTyped(evt);
            }
        });

        jLabel3.setText("Largura");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldLarguraRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAlturaRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(503, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAlturaRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldLarguraRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPanelFiguraGeometrica.addTab("Retângulo", jPanel2);

        jLabel4.setText("Raio");

        jTextFieldRaioCircunferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRaioCircunferenciaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldRaioCircunferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(536, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldRaioCircunferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jTabbedPanelFiguraGeometrica.addTab("Círculo", jPanel3);

        jTextFieldAlturaTrianguloRetangulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAlturaTrianguloRetanguloKeyTyped(evt);
            }
        });

        jLabel5.setText("Altura");

        jTextFieldLarguraTrianguloRetangulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLarguraTrianguloRetanguloKeyTyped(evt);
            }
        });

        jLabel6.setText("Largura");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldLarguraTrianguloRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAlturaTrianguloRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(503, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAlturaTrianguloRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldLarguraTrianguloRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPanelFiguraGeometrica.addTab("Triângulo Retângulo", jPanel4);

        jTextFieldAlturaTrianguloIsoceles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlturaTrianguloIsocelesActionPerformed(evt);
            }
        });
        jTextFieldAlturaTrianguloIsoceles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAlturaTrianguloIsocelesKeyTyped(evt);
            }
        });

        jLabel7.setText("Altura");

        jTextFieldLarguraTrianguloIsoceles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLarguraTrianguloIsocelesKeyTyped(evt);
            }
        });

        jLabel8.setText("Largura");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldLarguraTrianguloIsoceles, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAlturaTrianguloIsoceles, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(503, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldAlturaTrianguloIsoceles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldLarguraTrianguloIsoceles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPanelFiguraGeometrica.addTab("Triângulo Isosceles", jPanel5);

        jTextFieldAX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAXKeyTyped(evt);
            }
        });

        jLabel9.setText("Ponto A");

        jTextFieldBX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBXKeyTyped(evt);
            }
        });

        jLabel10.setText("Ponto B");

        jLabel11.setText("X");

        jLabel12.setText("Y");

        jLabel13.setText("Ponto C");

        jTextFieldCX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCXKeyTyped(evt);
            }
        });

        jTextFieldCY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCYKeyTyped(evt);
            }
        });

        jTextFieldBY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBYKeyTyped(evt);
            }
        });

        jTextFieldAY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAYKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldBX))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAX, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCX)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldBY)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAY, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCY, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel11)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldCX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextFieldAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPanelFiguraGeometrica.addTab("Triângulo genérico", jPanel6);

        jTextFieldBaseParalelogramo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBaseParalelogramoKeyTyped(evt);
            }
        });

        jLabel14.setText("Base");

        jTextFieldAlturaParalelogramo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAlturaParalelogramoKeyTyped(evt);
            }
        });

        jLabel15.setText("Altura");

        jLabel18.setText("Lado Inclinado");

        jTextFieldLadoInclinadoParalelogramo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLadoInclinadoParalelogramoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBaseParalelogramo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAlturaParalelogramo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLadoInclinadoParalelogramo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldBaseParalelogramo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldAlturaParalelogramo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldLadoInclinadoParalelogramo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPanelFiguraGeometrica.addTab("Paralelogramo", jPanel7);

        jButtonCalcular.setText("Calcular área e perímetro");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanelFiguraGeometrica)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPanelFiguraGeometrica, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLadoQuadradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLadoQuadradoKeyTyped
        char caractereDigitado = evt.getKeyChar();

        if (!Character.isDigit(caractereDigitado) && caractereDigitado != '.')
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLadoQuadradoKeyTyped

    private void jTextFieldAlturaRetanguloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAlturaRetanguloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlturaRetanguloKeyTyped

    private void jTextFieldLarguraRetanguloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLarguraRetanguloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLarguraRetanguloKeyTyped

    private void jTextFieldRaioCircunferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRaioCircunferenciaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRaioCircunferenciaKeyTyped

    private void jTextFieldAlturaTrianguloRetanguloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAlturaTrianguloRetanguloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlturaTrianguloRetanguloKeyTyped

    private void jTextFieldLarguraTrianguloRetanguloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLarguraTrianguloRetanguloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLarguraTrianguloRetanguloKeyTyped

    private void jTextFieldAlturaTrianguloIsocelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlturaTrianguloIsocelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlturaTrianguloIsocelesActionPerformed

    private void jTextFieldAlturaTrianguloIsocelesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAlturaTrianguloIsocelesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlturaTrianguloIsocelesKeyTyped

    private void jTextFieldLarguraTrianguloIsocelesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLarguraTrianguloIsocelesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLarguraTrianguloIsocelesKeyTyped

    private void jTextFieldAXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAXKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAXKeyTyped

    private void jTextFieldBXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBXKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBXKeyTyped

    private void jTextFieldCXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCXKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCXKeyTyped

    private void jTextFieldCYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCYKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCYKeyTyped

    private void jTextFieldBYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBYKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBYKeyTyped

    private void jTextFieldAYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAYKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAYKeyTyped

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed

        //Ação do botão calcular
        int indiceEscolhido = jTabbedPanelFiguraGeometrica.getSelectedIndex();
        
        double area, perimetro;
        
        switch (indiceEscolhido){
            case 0: // O quadrado foi escolhido
                double ladoQuadrado = Double.parseDouble(jTextFieldLadoQuadrado.getText());
                Quadrado q = new Quadrado(ladoQuadrado); //instanciou o Quadrado
                area = q.calcularArea();
                perimetro = q.calcularPerimetro();
                javax.swing.JOptionPane.showMessageDialog(this, "Área do Quadrado: " + String.format("%.2f", area));
                javax.swing.JOptionPane.showMessageDialog(this, "Perímetro do Quadrado: " + String.format("%.2f", perimetro));
                painelDesenhoQuadrado.desenharFigura("quadrado", ladoQuadrado, ladoQuadrado);
                break;
            case 1: // O retângulo foi escolhido
                double larguraRetangulo = Double.parseDouble(jTextFieldLarguraRetangulo.getText());
                double alturaRetangulo = Double.parseDouble(jTextFieldAlturaRetangulo.getText());
                Retangulo r = new Retangulo(larguraRetangulo, alturaRetangulo); //instanciou o Retângulo
                area = r.calcularArea();
                perimetro = r.calcularPerimetro();
                javax.swing.JOptionPane.showMessageDialog(this, "Área do Retângulo: " + String.format("%.2f", area));
                javax.swing.JOptionPane.showMessageDialog(this, "Perímetro do Retângulo: " + String.format("%.2f", perimetro));
                break;
            case 2: // O triângulo retângulo foi escolhido
                double larguraTrianguloRetangulo = Double.parseDouble(jTextFieldLarguraTrianguloRetangulo.getText());
                double alturaTrianguloRetangulo = Double.parseDouble(jTextFieldAlturaTrianguloRetangulo.getText());
                TrianguloRetangulo tr = new TrianguloRetangulo(larguraTrianguloRetangulo, alturaTrianguloRetangulo); //instanciou o Retângulo
                area = tr.calcularArea();
                perimetro = tr.calcularPerimetro();
                javax.swing.JOptionPane.showMessageDialog(this, "Área do Triangulo Retângulo: " + String.format("%.2f", area));
                javax.swing.JOptionPane.showMessageDialog(this, "Perímetro do Triangulo Retângulo: " + String.format("%.2f", perimetro));
                break;
            case 3: // A circunferencia foi escolhida
                double raioCircunferencia = Double.parseDouble(jTextFieldRaioCircunferencia.getText());
                Circunferencia c = new Circunferencia(raioCircunferencia); //instanciou o Quadrado
                area = c.calcularArea();
                perimetro = c.calcularPerimetro();
                javax.swing.JOptionPane.showMessageDialog(this, "Área da Circunferência: " + String.format("%.2f", area));
                javax.swing.JOptionPane.showMessageDialog(this, "Perímetro da Circunferência: " + String.format("%.2f", perimetro));
                break;
            case 4:
                double alturaTrianguloIsosceles = Double.parseDouble(jTextFieldAlturaTrianguloIsoceles.getText());        
                double larguraTrianguloIsosceles = Double.parseDouble(jTextFieldLarguraTrianguloIsoceles.getText());        
                TrianguloIsoceles ti = new TrianguloIsoceles(larguraTrianguloIsosceles, alturaTrianguloIsosceles);
                area = ti.calcularArea();
                perimetro = ti.calcularPerimetro();
                javax.swing.JOptionPane.showMessageDialog(this, "Área do Triângulo Isosceles: " + String.format("%.2f", area));
                javax.swing.JOptionPane.showMessageDialog(this, "Perímetro do Triângulo Isosceles: " + String.format("%.2f", perimetro));
                break;
            case 5:
                double[][] matrizVertices = new double[3][2];
            
                // Vértice A (Linha 0)
                matrizVertices[0][0] = Double.parseDouble(jTextFieldAX.getText()); 
                matrizVertices[0][1] = Double.parseDouble(jTextFieldAY.getText());

                // Vértice B (Linha 0)
                matrizVertices[1][0] = Double.parseDouble(jTextFieldBX.getText()); 
                matrizVertices[1][1] = Double.parseDouble(jTextFieldBY.getText());

                // Vértice C (Linha 0)
                matrizVertices[2][0] = Double.parseDouble(jTextFieldCX.getText()); 
                matrizVertices[2][1] = Double.parseDouble(jTextFieldCY.getText());
                    
                TrianguloGenerico tg = new TrianguloGenerico(matrizVertices);
                area = tg.calcularArea();
                perimetro = tg.calcularPerimetro();
                javax.swing.JOptionPane.showMessageDialog(this, "Área do Triângulo Genérico: " + String.format("%.2f", area));
                javax.swing.JOptionPane.showMessageDialog(this, "Perímetro do Triângulo Genérico: " + String.format("%.2f", perimetro));
                break;
            case 6:
                double baseParalelogramo = Double.parseDouble(jTextFieldBaseParalelogramo.getText());
                double alturaParalelogramo = Double.parseDouble(jTextFieldAlturaParalelogramo.getText());
                double ladoInclinadoParalelogramo = Double.parseDouble(jTextFieldLadoInclinadoParalelogramo.getText());
                if(ladoInclinadoParalelogramo < alturaParalelogramo) {javax.swing.JOptionPane.showMessageDialog(null, "O lado deve ser maior que a altura!");}
                else{
                Paralelogramo p = new Paralelogramo (baseParalelogramo, alturaParalelogramo, ladoInclinadoParalelogramo); //instanciou o Retângulo
                area = p.calcularArea();
                perimetro = p.calcularPerimetro();
                javax.swing.JOptionPane.showMessageDialog(this, "Área do Paralelogramo: " + String.format("%.2f", area));
                javax.swing.JOptionPane.showMessageDialog(this, "Perímetro do Paralelogramo: " + String.format("%.2f", perimetro));}
                break;
        }
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jTextFieldBaseParalelogramoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBaseParalelogramoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBaseParalelogramoKeyTyped

    private void jTextFieldAlturaParalelogramoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAlturaParalelogramoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlturaParalelogramoKeyTyped

    private void jTextFieldLadoInclinadoParalelogramoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLadoInclinadoParalelogramoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLadoInclinadoParalelogramoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPanelFiguraGeometrica;
    private javax.swing.JTextField jTextFieldAX;
    private javax.swing.JTextField jTextFieldAY;
    private javax.swing.JTextField jTextFieldAlturaParalelogramo;
    private javax.swing.JTextField jTextFieldAlturaRetangulo;
    private javax.swing.JTextField jTextFieldAlturaTrianguloIsoceles;
    private javax.swing.JTextField jTextFieldAlturaTrianguloRetangulo;
    private javax.swing.JTextField jTextFieldBX;
    private javax.swing.JTextField jTextFieldBY;
    private javax.swing.JTextField jTextFieldBaseParalelogramo;
    private javax.swing.JTextField jTextFieldCX;
    private javax.swing.JTextField jTextFieldCY;
    private javax.swing.JTextField jTextFieldLadoInclinadoParalelogramo;
    private javax.swing.JTextField jTextFieldLadoQuadrado;
    private javax.swing.JTextField jTextFieldLarguraRetangulo;
    private javax.swing.JTextField jTextFieldLarguraTrianguloIsoceles;
    private javax.swing.JTextField jTextFieldLarguraTrianguloRetangulo;
    private javax.swing.JTextField jTextFieldRaioCircunferencia;
    private PainelDesenho painelDesenhoQuadrado;
    // End of variables declaration//GEN-END:variables
}
