/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2830482421025
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanelFiguraGeometrica = new javax.swing.JTabbedPane();
        jPanelQuadrado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLadoQuadrado = new javax.swing.JTextField();
        jPanelRetangulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAlturaRetangulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLarguraRetangulo = new javax.swing.JTextField();
        jPanelTrianguloRetangulo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAlturaTrianguloRetangulo = new javax.swing.JTextField();
        jTextFieldLarguraTrianguloRetangulo = new javax.swing.JTextField();
        jPanelCircunferencia = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldRaioCircunferencia = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cálculo de área e perímetro de figuras geométricas");

        jTabbedPanelFiguraGeometrica.setBackground(new java.awt.Color(255, 204, 204));

        jPanelQuadrado.setBackground(new java.awt.Color(255, 204, 204));
        jPanelQuadrado.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Lado:");

        jTextFieldLadoQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLadoQuadradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQuadradoLayout = new javax.swing.GroupLayout(jPanelQuadrado);
        jPanelQuadrado.setLayout(jPanelQuadradoLayout);
        jPanelQuadradoLayout.setHorizontalGroup(
            jPanelQuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuadradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldLadoQuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
        );
        jPanelQuadradoLayout.setVerticalGroup(
            jPanelQuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuadradoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelQuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldLadoQuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jTabbedPanelFiguraGeometrica.addTab("Quadrado", jPanelQuadrado);

        jPanelRetangulo.setBackground(new java.awt.Color(255, 204, 204));
        jPanelRetangulo.setForeground(new java.awt.Color(255, 204, 204));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Altura:");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Largura:");

        javax.swing.GroupLayout jPanelRetanguloLayout = new javax.swing.GroupLayout(jPanelRetangulo);
        jPanelRetangulo.setLayout(jPanelRetanguloLayout);
        jPanelRetanguloLayout.setHorizontalGroup(
            jPanelRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRetanguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelRetanguloLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAlturaRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRetanguloLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldLarguraRetangulo)))
                .addContainerGap(547, Short.MAX_VALUE))
        );
        jPanelRetanguloLayout.setVerticalGroup(
            jPanelRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRetanguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAlturaRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldLarguraRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jTabbedPanelFiguraGeometrica.addTab("Retângulo", jPanelRetangulo);

        jPanelTrianguloRetangulo.setBackground(new java.awt.Color(255, 204, 204));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Altura:");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Largura:");

        jTextFieldLarguraTrianguloRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLarguraTrianguloRetanguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTrianguloRetanguloLayout = new javax.swing.GroupLayout(jPanelTrianguloRetangulo);
        jPanelTrianguloRetangulo.setLayout(jPanelTrianguloRetanguloLayout);
        jPanelTrianguloRetanguloLayout.setHorizontalGroup(
            jPanelTrianguloRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrianguloRetanguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTrianguloRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTrianguloRetanguloLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAlturaTrianguloRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTrianguloRetanguloLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldLarguraTrianguloRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(546, Short.MAX_VALUE))
        );
        jPanelTrianguloRetanguloLayout.setVerticalGroup(
            jPanelTrianguloRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrianguloRetanguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTrianguloRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldAlturaTrianguloRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTrianguloRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldLarguraTrianguloRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jTabbedPanelFiguraGeometrica.addTab("Triângulo Retângulo", jPanelTrianguloRetangulo);

        jPanelCircunferencia.setBackground(new java.awt.Color(255, 204, 204));
        jPanelCircunferencia.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Raio:");

        jTextFieldRaioCircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRaioCircunferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCircunferenciaLayout = new javax.swing.GroupLayout(jPanelCircunferencia);
        jPanelCircunferencia.setLayout(jPanelCircunferenciaLayout);
        jPanelCircunferenciaLayout.setHorizontalGroup(
            jPanelCircunferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCircunferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldRaioCircunferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(564, Short.MAX_VALUE))
        );
        jPanelCircunferenciaLayout.setVerticalGroup(
            jPanelCircunferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCircunferenciaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelCircunferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldRaioCircunferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jTabbedPanelFiguraGeometrica.addTab("Circunferencia", jPanelCircunferencia);

        jButtonCalcular.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCalcular.setForeground(new java.awt.Color(255, 204, 204));
        jButtonCalcular.setText("Calcular área e perímetro");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelFiguraGeometrica)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelFiguraGeometrica, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        //Ação do botão calcular
        int indiceEscolhido = jTabbedPanelFiguraGeometrica.getSelectedIndex();
        
        double area, perimetro;
        
        switch (indiceEscolhido){
            case 0: // O quadrado foi escolhido
                double ladoQuadrado = Double.parseDouble(jTextFieldLadoQuadrado.getText());
                Quadrado q = new Quadrado(ladoQuadrado); //instanciou o Quadrado
                area = q.calcularArea();
                perimetro = q.calcularPerimetro();
                javax.swing.JOptionPane.showMessageDialog(this, "Área do Quadrado: " + String.format("%.2f", area));
                javax.swing.JOptionPane.showMessageDialog(this, "Perímetro do Quadrado: " + String.format("%.2f", perimetro));
                break;
            case 1: // O retângulo foi escolhido
                double larguraRetangulo = Double.parseDouble(jTextFieldLarguraRetangulo.getText());
                double alturaRetangulo = Double.parseDouble(jTextFieldAlturaRetangulo.getText());
                Retangulo r = new Retangulo(larguraRetangulo, alturaRetangulo); //instanciou o Retângulo
                area = r.calcularArea();
                perimetro = r.calcularPerimetro();
                javax.swing.JOptionPane.showMessageDialog(this, "Área do Retângulo: " + String.format("%.2f", area));
                javax.swing.JOptionPane.showMessageDialog(this, "Perímetro do Retângulo: " + String.format("%.2f", perimetro));
                break;
            case 2: // O triângulo retângulo foi escolhido
                double larguraTrianguloRetangulo = Double.parseDouble(jTextFieldLarguraTrianguloRetangulo.getText());
                double alturaTrianguloRetangulo = Double.parseDouble(jTextFieldAlturaTrianguloRetangulo.getText());
                TrianguloRetangulo tr = new TrianguloRetangulo(larguraTrianguloRetangulo, alturaTrianguloRetangulo); //instanciou o Retângulo
                area = tr.calcularArea();
                perimetro = tr.calcularPerimetro();
                javax.swing.JOptionPane.showMessageDialog(this, "Área do Triangulo Retângulo: " + String.format("%.2f", area));
                javax.swing.JOptionPane.showMessageDialog(this, "Perímetro do Triangulo Retângulo: " + String.format("%.2f", perimetro));
                break;
            case 3: // A circunferencia foi escolhida
                double raioCircunferencia = Double.parseDouble(jTextFieldRaioCircunferencia.getText());
                Circunferencia c = new Circunferencia(raioCircunferencia); //instanciou o Quadrado
                area = c.calcularArea();
                perimetro = c.calcularPerimetro();
                javax.swing.JOptionPane.showMessageDialog(this, "Área da Circunferência: " + String.format("%.2f", area));
                javax.swing.JOptionPane.showMessageDialog(this, "Perímetro da Circunferência: " + String.format("%.2f", perimetro));
                break;
        }
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jTextFieldRaioCircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRaioCircunferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRaioCircunferenciaActionPerformed

    private void jTextFieldLarguraTrianguloRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLarguraTrianguloRetanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLarguraTrianguloRetanguloActionPerformed

    private void jTextFieldLadoQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLadoQuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLadoQuadradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelCircunferencia;
    private javax.swing.JPanel jPanelQuadrado;
    private javax.swing.JPanel jPanelRetangulo;
    private javax.swing.JPanel jPanelTrianguloRetangulo;
    private javax.swing.JTabbedPane jTabbedPanelFiguraGeometrica;
    private javax.swing.JTextField jTextFieldAlturaRetangulo;
    private javax.swing.JTextField jTextFieldAlturaTrianguloRetangulo;
    private javax.swing.JTextField jTextFieldLadoQuadrado;
    private javax.swing.JTextField jTextFieldLarguraRetangulo;
    private javax.swing.JTextField jTextFieldLarguraTrianguloRetangulo;
    private javax.swing.JTextField jTextFieldRaioCircunferencia;
    // End of variables declaration//GEN-END:variables
}
